version: '3'

services:
  api:
    networks:
      hc-network:
        ipv4_address: 172.25.0.11
  thumbor:
    networks:
      hc-network:
        ipv4_address: 172.25.0.13

networks:
  hc-network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.25.0.0/16
