version: '3'

services:
  api:
    build: .
    links:
      - mongo
      - maildev
    command: yarn run dev
    volumes:
      - .:/API
  mongo:
    image: mongo
    command: "--smallfiles --logpath=/dev/null"
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
  thumbor:
    image: apsl/thumbor
