version: '3'

services:
  api:
    build: .
    ports:
      - "3030:3030"
      - "9229:9229" # node inspect
    links:
      - mongo
      - maildev
    environment:
      - NODE_ENV=development
    command: yarn run dev
    volumes:
      - .:/API
      - docker_config:/API/config
  mongo:
    image: mongo
    command: "--smallfiles --logpath=/dev/null"
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
volumes:
  docker_config:
