version: '3'

services:
  api:
    container_name: api_api
    hostname: api_api
    image: humanconnection/api-feathers:edge
    build:
      context: .
    environment:
      - NODE_ENV=staging
    depends_on:
      - maildev
      - thumbor
    ports:
      - "3030:3030"
    networks:
      - hc-network

  maildev:
    container_name: api_maildev
    hostname: api_maildev
    image: djfarrelly/maildev
    networks:
      - hc-network
    ports:
      - "1080:80"
      - "1025:25"

  thumbor:
    container_name: api_thumbor
    hostname: api_thumbor
    image: apsl/thumbor
    networks:
      - hc-network
    ports:
      - "8000:8000"

  dns-proxy-server:
    image: defreitas/dns-proxy-server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
    ports:
      - 5380:5380
    hostname: dns.mageddo

networks:
  hc-network:
    driver: bridge
    ipam:
      driver: default
