version: '3.5'

services:
  api:
    container_name: api
    hostname: api
    build: .
    depends_on:
      - mongo
    networks:
      - hc-network

  mongo:
    image: mongo
    networks:
      - hc-network
    command: "--smallfiles --logpath=/dev/null"

  dns-proxy-server:
    image: defreitas/dns-proxy-server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
    ports:
      - 5380:5380
    hostname: dns.mageddo
    networks:
      - hc-network

networks:
  hc-network:
    name: hc-network
    driver: bridge
    ipam:
      driver: default
