version: '3.5'

services:
  api:
    image: humanconnection/api-feathers:edge
    build:
      context: .
    environment:
      - NODE_ENV=staging
    depends_on:
      - maildev
      - thumbor
    ports:
      - "3030:3030"
    networks:
      - hc-network

  maildev:
    image: djfarrelly/maildev
    networks:
      - hc-network
    ports:
      - "1080:80"
      - "1025:25"

  thumbor:
    container_name: thumbor
    hostname: thumbor
    image: apsl/thumbor
    networks:
      - hc-network
    ports:
      - "8000:8000"

networks:
  hc-network:
    name: hc-network
    driver: bridge
    ipam:
      driver: default
